jwt:
  # yellowsunn-spring-boot-jwt-secret-key-yellowsunn-spring-boot-jwt-secret-key (base64)
  secret: eWVsbG93c3Vubi1zcHJpbmctYm9vdC1qd3Qtc2VjcmV0LWtleS15ZWxsb3dzdW5uLXNwcmluZy1ib290LWp3dC1zZWNyZXQta2V5